param (
    $SubscriptionId,
    $PAI_IID,
    $PAI_TOKEN,
    $EventhubNamespace,
    $FunctionAppName,
    $ResourceGroupLocation  = "westus2",
    $ResourceGroupName = "packetai-log-forwarder-rg",
    $EventhubName = "packetai-eventhub",
    $FunctionName = "packetai-function",
    $DiagnosticSettingName = "packetai-activity-logs-diagnostic-setting",
    $PacketAISite = "vector-ingester-logpatterns.packetai.co",
    $Environment = "AzureCloud",
)

if (-Not ($SubscriptionId -And $PAI_IID -And $PAI_TOKEN)) { Throw "`SubscriptionId`, `PAI_IID`, and `PAI_TOKEN` are required." }

Set-AzContext -SubscriptionId $SubscriptionId

$code = (New-Object System.Net.WebClient).DownloadString("https://raw.githubusercontent.com/PacketAI/azure-logs-forwarder/main/index.js")

New-AzResourceGroup -Name $ResourceGroupName -Location $ResourceGroupLocation

$environment = Get-AzEnvironment -Name $Environment
$endpointSuffix = $environment.StorageEndpointSuffix
$securePAI_IID = ConvertTo-SecureString $PAI_IID -AsPlainText -Force
$securePAI_TOKEN = ConvertTo-SecureString $PAI_TOKEN -AsPlainText -Force

$deploymentArgs = @{
    TemplateUri = "https://raw.githubusercontent.com/PacketAI/azure-logs-forwarder/main/parent_template.json"
    ResourceGroupName = $ResourceGroupName
    functionCode = $code
    PAI_IID = $securePAI_IID
    PAI_TOKEN = $PAI_TOKEN
    location = $ResourceGroupLocation
    eventHubName = $EventhubName
    functionName = $FunctionName
    packetAISite = $PacketAISite
    endpointSuffix = $endpointSuffix
}

# Use values if parameters passed, otherwise we rely on the default value generated by the ARM template
if ($EventhubNamespace) { $deploymentArgs["eventhubNamespace"] = $EventhubNamespace }
if ($FunctionAppName) { $deploymentArgs["functionAppName"] = $FunctionAppName }

try {
    $output = New-AzResourceGroupDeployment @deploymentArgs -Verbose -ErrorAction Stop
    # Get the generated globally-unique eventhub namespace
    $EventhubNamespace = $output.Outputs.eventHubNamespace.Value
} catch {
    Write-Error $_
    Return
}

try {
    New-AzDeployment `
        -TemplateUri "https://raw.githubusercontent.com/PacketAI/azure-logs-forwarder/main/activity_log_diagnostic_settings.json" `
        -eventHubNamespace $EventhubNamespace `
        -eventHubName $EventhubName `
        -settingName $DiagnosticSettingName `
        -resourceGroup $ResourceGroupName `
        -Location $ResourceGroupLocation `
        -Verbose `
        -ErrorAction Stop
} catch {
    Write-Error $_
    Return
}